kind: Service
apiVersion: v1
metadata:
  name:  redis-leader
  labels:
    app: redis
    role: leader
    tier: backend
spec:
  selector:
    app: redis
    role: leader
    tier: backend
  ports:
  - name:  rediss-port
    port:  6379
    targetPort:  6379
