apiVersion: v1
kind: Deployment
metadata:
  name:  nginx-dep
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image:  nginx:1.14.2
        name:  nginx-container
        ports:
        - containerPort:  80
